# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resultScreen.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1076, 898)
        Form.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.backButton = QtWidgets.QPushButton(Form)
        self.backButton.setGeometry(QtCore.QRect(20, 20, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 90, 1076, 808))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget.setObjectName("tabWidget")
        self.handVisual = QtWidgets.QWidget()
        self.handVisual.setObjectName("handVisual")
        self.pictureLabel = QtWidgets.QLabel(self.handVisual)
        self.pictureLabel.setGeometry(QtCore.QRect(210, 60, 640, 480))
        self.pictureLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.pictureLabel.setObjectName("pictureLabel")
        self.explanationHandVisualiser = QtWidgets.QLabel(self.handVisual)
        self.explanationHandVisualiser.setGeometry(QtCore.QRect(0, 620, 1076, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.explanationHandVisualiser.setFont(font)
        self.explanationHandVisualiser.setStyleSheet("background-color: rgb(160, 160, 160);")
        self.explanationHandVisualiser.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.explanationHandVisualiser.setObjectName("explanationHandVisualiser")
        self.tabWidget.addTab(self.handVisual, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 1071, 771))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.facePieChart = QtWidgets.QLabel(self.tab_3)
        self.facePieChart.setGeometry(QtCore.QRect(210, 130, 640, 480))
        self.facePieChart.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.facePieChart.setObjectName("facePieChart")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.faceScatter = QtWidgets.QLabel(self.tab_4)
        self.faceScatter.setGeometry(QtCore.QRect(210, 130, 640, 480))
        self.faceScatter.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.faceScatter.setObjectName("faceScatter")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tabWidget.addTab(self.tab, "")
        self.analysis = QtWidgets.QWidget()
        self.analysis.setObjectName("analysis")
        self.explanationText = QtWidgets.QLabel(self.analysis)
        self.explanationText.setGeometry(QtCore.QRect(0, 30, 1076, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.explanationText.setFont(font)
        self.explanationText.setStyleSheet("background-color: rgb(160, 160, 160);")
        self.explanationText.setText("")
        self.explanationText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.explanationText.setObjectName("explanationText")
        self.score = QtWidgets.QLabel(self.analysis)
        self.score.setGeometry(QtCore.QRect(0, 250, 1076, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.score.setFont(font)
        self.score.setText("")
        self.score.setAlignment(QtCore.Qt.AlignCenter)
        self.score.setObjectName("score")
        self.scorePic = QtWidgets.QLabel(self.analysis)
        self.scorePic.setGeometry(QtCore.QRect(290, 390, 480, 360))
        self.scorePic.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.scorePic.setText("")
        self.scorePic.setObjectName("scorePic")
        self.tabWidget.addTab(self.analysis, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.speechPie = QtWidgets.QLabel(self.tab_2)
        self.speechPie.setGeometry(QtCore.QRect(230, 130, 640, 480))
        self.speechPie.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.speechPie.setObjectName("speechPie")
        self.tabWidget.addTab(self.tab_2, "")
        self.titleLabel = QtWidgets.QLabel(Form)
        self.titleLabel.setGeometry(QtCore.QRect(170, 20, 701, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setText("")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.backButton.setText(_translate("Form", "Back"))
        self.pictureLabel.setText(_translate("Form", "TextLabel"))
        self.explanationHandVisualiser.setText(_translate("Form", "This heatmap visualises the positions of the hands.\n"
"The concentrated parts of the map (yellow-red) indicate a accumulation of identified \n"
"hands at a given position over the time of the recording. "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.handVisual), _translate("Form", "Hand Visualiser"))
        self.facePieChart.setText(_translate("Form", "TextLabel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Form", "Pie Chart View"))
        self.faceScatter.setText(_translate("Form", "TextLabel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Form", "Timeline View"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Facial Expression Analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analysis), _translate("Form", "Text Emotions Analysis"))
        self.speechPie.setText(_translate("Form", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Speech Emotions Analysis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
